version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: car_search_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/car_search_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - >
        echo "=== Running migrations ===" &&
        alembic upgrade head &&
        echo "=== Populating database ===" &&
        python -m app.scripts.populate_db --number 100 &&
        echo "=== Starting MCP Server ===" &&
        python -m app.mcp.server --host 0.0.0.0 --port 5000

volumes:
  db_data:
